
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LIT_INT = 37;
  public static final int SEMI = 12;
  public static final int INT = 23;
  public static final int PRINTLN = 5;
  public static final int OUT = 4;
  public static final int LESS = 31;
  public static final int MINUS = 32;
  public static final int STATIC = 7;
  public static final int NOT = 33;
  public static final int AND = 29;
  public static final int LP = 17;
  public static final int COMMA = 36;
  public static final int BOOL = 19;
  public static final int CLASS = 2;
  public static final int RP = 18;
  public static final int PLUS = 34;
  public static final int ASSIGN = 30;
  public static final int MAIN = 3;
  public static final int IF = 22;
  public static final int THIS = 26;
  public static final int DOT = 11;
  public static final int EOF = 0;
  public static final int LC = 15;
  public static final int SYSTEM = 9;
  public static final int LB = 13;
  public static final int RETURN = 25;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int RC = 16;
  public static final int RB = 14;
  public static final int IDENT = 38;
  public static final int VOID = 10;
  public static final int TIMES = 35;
  public static final int ELSE = 20;
  public static final int WHILE = 27;
  public static final int PUBLIC = 6;
  public static final int EXTENDS = 21;
  public static final int LIT_BOOL = 39;
  public static final int STRING = 8;
  public static final int LENGTH = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "MAIN",
  "OUT",
  "PRINTLN",
  "PUBLIC",
  "STATIC",
  "STRING",
  "SYSTEM",
  "VOID",
  "DOT",
  "SEMI",
  "LB",
  "RB",
  "LC",
  "RC",
  "LP",
  "RP",
  "BOOL",
  "ELSE",
  "EXTENDS",
  "IF",
  "INT",
  "NEW",
  "RETURN",
  "THIS",
  "WHILE",
  "LENGTH",
  "AND",
  "ASSIGN",
  "LESS",
  "MINUS",
  "NOT",
  "PLUS",
  "TIMES",
  "COMMA",
  "LIT_INT",
  "IDENT",
  "LIT_BOOL"
  };
}

